version: "3.9"
services:
  api:
    build: .
    container_name: banking_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    container_name: banking_dashboard
    environment:
      - DASHBOARD_API_BASE=http://api:8000/api/v1
    ports:
      - "8501:8501"
    depends_on:
      - api

  mongo:
    image: mongo:6
    container_name: banking_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: banking_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:


